name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Context
        run: echo "${{ toJSON(github) }}"

      - name: Set up PHP
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: '8.2' # Or your preferred PHP version

      - name: Install Dependencies
        run: |
          composer install --optimize-autoloader
          composer dump-autoload

      - name: Check Environment
        run: |
          php -v
          composer --version
          php artisan --version

      - name: Run Pest Tests
        run: |
          php artisan config:clear
          php artisan cache:clear
          ./vendor/bin/pest --verbose